#!/bin/bash

COMMAND="${@:2}"
COMMAND_TYPE=$1

if test $COMMAND_TYPE = "adb" || test $COMMAND_TYPE = "fastboot" ; then

  DEVICES=`$COMMAND_TYPE devices | grep -v "List" | awk '{print$1}'`
  DEVICE_COUNT=`echo $DEVICES | wc -w`

  if [ $DEVICE_COUNT == 0 ]; then
    echo "No device connected"
    exit
  fi

  for device in $DEVICES
  do
    echo ""
    echo "$COMMAND_TYPE -s $device $COMMAND"
    $COMMAND_TYPE -s $device $COMMAND
    if ! [ $? -eq 0 ]; then
      echo "$COMMAND couldn't fully execute, check for errors."
      echo "Write commands according to 'adb --help'"
      exit
    fi
  done

else
  echo "Please use the command adb or fastboot"
fi
